# -*- coding: utf-8 -*-
"""
Created on Fri Jun 24 14:53:01 2022

opens path generated by A* algorithm

@author: hudso
"""
import matplotlib.pyplot as plt
import pickle

with open('path', 'rb') as f:
    path = pickle.load(f)

def scatterPlotPoints(ax, color, *args):
    x = []
    y = []
    z = []
    for point in args:
        x.append(point[0])
        y.append(point[1])
        z.append(point[2])
    ax.scatter3D(x, y, z, c=color)


def scatterPlotList(ax, color, points):
    x = []
    y = []
    z = []
    for point in points:
        x.append(point[0])
        y.append(point[1])
        z.append(point[2])
    ax.scatter3D(x, y, z, c=color)
    
fig = plt.figure()
axis = fig.add_subplot(111, projection='3d')

scatterPlotList(axis, "r", path)

axis.set_box_aspect([ub - lb for lb, ub in (getattr(axis, f'get_{a}lim')() for a in 'xyz')])
plt.show()